apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: https://github.com/tu-usuario/k8s-prometheus-grafana-argocd-demo.git  # Reemplazar con tu repositorio
    targetRevision: HEAD
    path: monitoring/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
